language: ruby
before_script: 
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
rvm:
  - 1.8.7
  - 1.9.3
  - rbx
  - jruby
env:
  - DB=mysql DB_USERNAME=root
  - DB=postgresql DB_USERNAME=postgres
gemfile:
  - gemfiles/refinery-2.0.0
  - gemfiles/refinery-2.0.1
  - gemfiles/refinery-2.0.2
  - gemfiles/refinery-2-0-stable-branch
  - gemfiles/refinery-edge