language: ruby
before_script: 
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake refinery:testing:dummy_app
  - bundle exec rake prepare_ci_env
  - "sh -c 'cd spec/dummy && bundle exec rake db:create db:migrate RAILS_ENV=test AUTO_ACCEPT=true'"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - ree
env:
  - DB=mysql DB_USERNAME=root
  - DB=postgresql DB_USERNAME=postgres
gemfile:
  - gemfiles/refinery-2.0.0
  - gemfiles/refinery-2.0.1
  - gemfiles/refinery-2.0.2
  - gemfiles/refinery-2-0-stable-branch
  - gemfiles/refinery-edge