language: ruby
before_script: 
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
  - "sh -c 'cd spec/dummy && bundle exec rake db:create db:migrate RAILS_ENV=test AUTO_ACCEPT=true'"
rvm:
  - 1.8.7
  - 1.9.3
  - rbx
  - jruby
env:
  - DB=mysql DB_USERNAME=root
  - DB=postgresql DB_USERNAME=postgres
